### PR TITLE
removed button and lcd display logic

### PR DESCRIPTION
**Pull request by JayPankajPatel**
Referring to Issue #7:

# What was done
Removed any logic that resembled user button and LCD display

# How was it done
Found functions and variables that were associated with the User button and LCD display and deleted them, this includes
- Button Macro
- Button GPIO Input Initialization
- Button Reading Functions
- Button State Management Functions
- LCD header file
- LCD init function
- LCD backlight function
- LCD functions starting with display
- LCD update functions

### CODE REVIEW

**Comment by W0481966** [comment]
That's a good start, but there are still some things to do before it's complete:

* The `delay(10);` at the end of `loop()` should also be removed - that's part of the [button debouncing](https://docs.arduino.cc/built-in-examples/digital/Debounce) code. Sorry, I could've made that code clearer.
* The LCD display should also be removed from the [schematic](/NSCC-workterm-treadmill-2023/treadmill-driver/tree/master/kicad/schematic-final) and the [image of the schematic](/NSCC-workterm-treadmill-2023/treadmill-driver/blob/master/docs/schematic-v0.3.png) that's used in the README.

**Comment by JayPankajPatel** [comment]
Will do, give me some time to install kicad, I have only worked with PCB editor and the OrCAD ecosystem before.

**Comment by JayPankajPatel** [comment]
Okay I updated the schematic and removed old pictures from the docs. Let me know if there are any issues with it.

**Comment by W0481966** [comment]
Good job!

If you're thinking of doing any further work, I can't promise that I'll merge it into master. The work term is over and I'm no longer at NSCC, so I don't have access to the treadmill for testing. I can create another branch to merge into if you want to keep going though, and next year's students might use it.

**Comment by JayPankajPatel** [comment]
Hey Chris,
Thanks for the heads up,
I will contribute if issues are open and I have some free time, so don't
worry about it.

Best Regards,

Jay Patel

**Pull request merged**
